# Generated by Django 5.0.2 on 2026-06-25 20:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SequenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled_sequence', help_text='Sequence title/identifier (from FASTA header)', max_length=100)),
                ('sequence', models.CharField(max_length=130, validators=[django.core.validators.RegexValidator(code='invalid_sequence', message='Sequence must contain only valid amino acid letters (ACDEFGHIKLMNPQRSTVWY)', regex='^[acdefghiklmnpqrstvwxyACDEFGHIKLMNPQRSTVWY]+$'), django.core.validators.MaxLengthValidator(130)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=10)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.FloatField(default=0)),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('prediction_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence_analyzer.predictionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submit_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_token', models.UUIDField(default=uuid.uuid4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
