# Generated by Django 5.0.2 on 2025-12-14 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_analyzer', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencesubmission',
            name='title',
            field=models.CharField(default='untitled_sequence', help_text='Sequence title/identifier (from FASTA header)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sequencesubmission',
            name='sequence',
            field=models.CharField(max_length=130, validators=[django.core.validators.RegexValidator(code='invalid_sequence', message='Sequence must contain only valid amino acid letters (ACDEFGHIKLMNPQRSTVWY)', regex='^[acdefghiklmnpqrstvwxyACDEFGHIKLMNPQRSTVWY]+$'), django.core.validators.MaxLengthValidator(130)]),
        ),
    ]
